//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payrollsystemsti
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAccount
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string SSN { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public System.DateTime Dob { get; set; }
        public string BasicRate { get; set; }
        public string FileName { get; set; }
        public byte[] ImageData { get; set; }
        public string Mobile { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Leaves { get; set; }
        public Nullable<int> Absents { get; set; }
        public Nullable<int> fingerID { get; set; }
    }
}
